version: '2'

services:
    redis:
        extends:
            file: docker/common.yml
            service: cache

    postgre:
        extends:
            file: docker/common.yml
            service: db

    django-app:
        extends:
            file: docker/common.yml
            service: app
#        build:
#            context: .
#            dockerfile: ./Dockerfile
        container_name: django-app-http
        command: runserver
        links:
            - postgre
            - redis
        depends_on:
            - postgre
            - redis

    nginx:
        extends:
            file: docker/common.yml
            service: proxy
        container_name: nginx-http
        volumes:
            - ./nginx/conf.d.http:/etc/nginx/conf.d:ro
        links:
            - django-app
