version: '2'

services:
    redis:
        extends:
            file: docker/common.yml
            service: cache

    postgre:
        extends:
            file: docker/common.yml
            service: db

    django-app:
        extends:
            file: docker/common.yml
            service: app
        build:
            context: .
            dockerfile: ./Dockerfile
        links:
            - postgre
            - redis
        depends_on:
            - postgre
            - redis

    nginx:
        extends:
            file: docker/common.yml
            service: proxy
        links:
            - django-app
